source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /blog/:year/:month/:day/:title.html
auto: true
pygments: true
safe: false
blogname: "Madhur@Web:~# :(){ :|: & };:"
blogurl: http://madhur.co.in
feedname: http://feeds.feedburner.com/madhur
github_user: madhur

projects:
  
  Beller: &beller
    title:     Beller
    languages: [Win32 Assembly]
    download:  https://github.com/madhur/CollegeCode/tree/master/winsock/bell
    name:        tagger
    description: >
      Beller is a winsock Application written in Win32 Assembly which plays a sound bell on a remote computer on a LAN. The aim is to wake up the person sitting there. The lists of connected hosts can be configured by the user.


  Error: &error
    title:     Error
    languages: [VC++]
    download:  /files/files/error10.zip
    description: >
      The program shows the error description corresponding to error number using FormatMessage API.
  
  Buffer: &buffer
    title:       Buffer
    languages:   [Assembly]
    download:  /files/files/buffer10.zip
    description: >
      The TSR displays the contents of keyboard buffer. Useful for MS-DOS system programmers.
  
  Interrupt List Viewer: &Interru
    title:       Interrupt List Viewer (IView)
    languages:   [Assembly]
    download:  https://github.com/madhur/CollegeCode/blob/master/Assembly/ass/IVIEW2.ASM
    description: >
     ImpExp displays all the functions imported and exported by the PE file. Similar to DUMPBIN /EXPORTS
  
  TSR Clock: &TSRClock
    title:       TSR Clock
    languages:   [Assembly]
    download:  https://github.com/madhur/CollegeCode/blob/master/Assembly/ass/SCREEN.ASM
    description: >
      This is a TSR written in Assembly language to display the clock on the DOS Screen.

  TSR Screen: &BHDraggableImageView
    title:       TSR Screen
    languages:   [Assembly]
    download: http://www.madhur.co.in/files/files/screen10.zip
    description: >
      This is a screen saver for DOS.
  

  LanTalk: &autoDoc
    title:       LanTalk
    languages:   [Win32 Assembly]
    download: https://github.com/madhur/CollegeCode/tree/master/winsock/netsend
    description: >
      LANChat is a chatting client which works over the LAN. The program uses the Windows Messenger Service Works only on Win2000/XP
  
  FileHeader: &Web-Utilities
    title:       FileHeader
    languages:   [Win32 Assembly]
    download: hhttps://github.com/madhur/CollegeCode/tree/master/WIN32ASM/header
    description: >
      File Header is an explorer shell extension which displays the complete information about the Portable Executable (PE ) file and header for DOS MZ files.. Current version only supports .exe extension. The program is useful for those involved in programming of packers, unpackers as it displays all header fields at a click of button.
  
  
  ImpExp: &Bash-Scripts
    title:       ImpExp
    languages:   [Win32 Assembly]
    download: https://github.com/madhur/CollegeCode/tree/master/WIN32ASM/impexp
    description: >
      ImpExp displays all the functions imported and exported by the PE file. Similar to DUMPBIN /EXPORTS
  
  VA2Offset: &MKV-Utilities
    title:       VA2Offset
    languages:   [Win32 Assembly]
    download: http://www.madhur.co.in/files/files/vaoffset10.zip
    description: >
      VA2Offset is a nifty utility to convert the virtual address seen under debuggers likesoftice,ollydbg etc to offsets of the file. Virtual address supplied can reside in any of the section or in header of the Portable Executable File.
  
  
  Windows Password Revelation: &Finder-Utilities
    title:       Windows Password Revelation
    languages:   [Win32 Assembly]
    download: http://www.madhur.co.in/files/files/plite10.zip
    description: >
      Demonstrates the use of Hooks in windows. This one shows a simple Mouse Hook to reveal asterisk passwords. Although the program runs on all Windows versions, the revelation will occur on only win9x systems.
  
  # 
  # Applescript Utilities:
  #   title:       Applescript Utilities
  #   languages:   Applescript
  #   description: >
  #     A collection of use applscripts that inculding file labeling, 'fn lock', timestamping files and controlling mplayer.
  
  
  Port Scanner: &Scripts
    title:       Port Scanner
    languages:   [VC++]
    download: https://github.com/madhur/CollegeCode/tree/master/winsock/portscan
    description: >
      Port Scanner scans the system’s ports and shows the open TCP and UDP ports.
  
  
  Transparent: &bashmarks
    title:       Transparent
    languages:   [Win32 Assembly]
    download: http://www.madhur.co.in/files/files/TRANS10.ZIP
    name:   bashmarks
    description: >
      Turn your Desktop Icon’s background color to transparent using this cool utility. The program remains in memory and consumes very little resources
  


